### PR TITLE
Windows install script

### PR DESCRIPTION
**Pull request by TheMultii**
I tested it on hyper-v with a clean installation of Windows 10 22H2 and Windows 11 24H2 vms.

### CODE REVIEW

**Comment by RENSAAS** [comment]
git remote add origin https://github.com/OWNER/REPOSITORY.git

**Comment by RENSAAS** [comment]
E7EB08AB 42D7 4AAB2D19229697AB

**Comment by RENSAAS** [comment]
Still trying to figure my "bitlocker KEY" @RENSAAS

**Comment by RENSAAS** [comment]
[rfc7533.txt.pdf](https://github.com/user-attachments/files/18171318/rfc7533.txt.pdf)

**Comment by RENSAAS** [comment]
[rfc7501.txt.pdf](https://github.com/user-attachments/files/18171319/rfc7501.txt.pdf)
[3docs/web-service-reference/createmanagedfolder.mdgit remote add origin https://github.com/OWNER/REPOSITORY.git](url)

**Comment by TheMultii** [comment]
Locked conversation due to spam

**Pull request merged**
